### ISSUE TITLE
Betterspeedtest.sh giving 0 Mbps download and upload.

### ISSUE THREAD

**Issue by Delta-Sigma** [richb-hanover/OpenWrtScripts#2]
Sorry for bothering you but I couldn't find a solution to this elsewhere. Running betterspeedtest.sh on my router gives 0 Mbps download and upload. It calculates pings correctly (or at least so it seems).

Following is an example output:
 ```
Download:  0 Mbps
  Latency: (in msec, 145 pings, 0.00% packet loss)
      Min: 159.731
    10pct: 160.422
   Median: 161.703
      Avg: 163.519
    90pct: 168.848
      Max: 202.956
.................................................................................................................................................
   Upload:  0 Mbps
  Latency: (in msec, 145 pings, 0.00% packet loss)
      Min: 180.264
    10pct: 181.101
   Median: 182.979
      Avg: 190.696
    90pct: 205.767
      Max: 389.738
```

I am using a TP-LINK WR741ND (AR71xx platform) as a wireless bridge... and running Gargoyle 1.6.2.2 (based on OpenWrt Attitude Adjustment 12.09.1)

I have tried different netperf servers as well.

Many thanks.

**Comment by richb-hanover** [comment]
Great question - thanks for asking.

The 0 Mbps result is because of the connection-rate-limiting I have installed on netperf.bufferbloat.net. (I regularly see the same IP address testing their speed once per minute for hours at a time - the rate limit knocks them off the air.)

I suspect that a) you had made multiple speed tests in the last 10 minutes or so; b) if you wait ~10 minutes, the test will work again. 

I'm seeking the sweet spot that allows people to make multiple tests in a relative short period while slowing those who've set up automated test systems that consume bandwidth and provide no value (to me, at least).

**Comment by Delta-Sigma** [comment]
I tried after about 18 hrs. Still the same. Could it be because of dynamic IP assigned by the ISP or something?

**Comment by richb-hanover** [comment]
Ahah! I wonder if netperf is missing. (I think its absence might be cause 0 mbps traffic.) To install it, use `opkg update; opkg install netperf` Then enter `which netperf` and let me know the result.

**Comment by Delta-Sigma** [comment]
Thank you for your quick response.

`which netperf` gives `/usr/bin/netperf`.

I was wondering if my access to netperf.bufferfloat.net was blocked for some reason, and tried pinging from my laptop. They failed. Could not find host. I wondered if for some reason my ISP was blocking netperf.bufferfloat.net. But then I looked up bufferfloat.net using whois. [https://whois.icann.org/en/lookup?name=bufferfloat.net](https://whois.icann.org/en/lookup?name=bufferfloat.net) and it says it cannot find it.
