### ISSUE TITLE
No results showing for BetterSpeedTest.sh

### ISSUE THREAD

**Issue by ChamaCR** [richb-hanover/OpenWrtScripts#7]
BetterSpeedTest.sh was running just fine, but since yesterday all I get is empty results (see attached screenshot)

<img width="711" alt="image" src="https://user-images.githubusercontent.com/38114515/119541634-e0fff600-bd4b-11eb-8f5e-4cea931e1b25.png">

Thanks!

**Comment by richb-hanover** [comment]
Hmmm... I'm not sure what is happening.  I had trouble with `netperf.bufferbloat.net` a week ago, but it's online and working for me.

Try testing a different bufferbloat server. Add `-H netperf-eu.bufferbloat.net` or `-H netperf-west.bufferbloat.net` to the command line

**Comment by zkzkzk2015** [comment]
I can confirm, netperf.bufferbloat.net is not working anymore, used in betterspeedtest.sh

**Comment by richb-hanover** [comment]
It is currently working for me. Have you been testing against netperf.bufferbloat.net frequently? There's an fail2ban script that detects and blocks constant/heavy use...

**Comment by zkzkzk2015** [comment]
Still not working, I think it worked until Monday or Tuesday and suddenly stopped. I tested it a couple of times lately. Maybe 5-10 times. That's it. Do you think my IP is blacklisted?

**Comment by richb-hanover** [comment]
Could be. Email your IP to me privately. You can find the address at http://test.richb-hanover.com <http://test.richb-hanover.com/>

Thanks.

**Comment by zkzkzk2015** [comment]
Thanks, it is working again.

**Comment by JayGoldberg** [comment]
Also not showing net speed output (0.00 Mbps) for me on newly installed `.opk` I really doubt I was blocked running it for the first time. Will try to debug, I assume it's something wrong with the call to `netperf`.

**Comment by richb-hanover** [comment]
@JayGoldberg It appears that OpenWrt has changed the ping program such that `ping gstatic.com` (for example) attempts to use an IPv6 address first. (At least, that's the only explanation I can find. I am unable to set up IPv6 service at my home.)

The workaround is to supply a "ping host" (`-p`), like this: `sh betterspeedtest.sh -p 1.1.1.1` 

------
Details: Here's a lookup for `gstatic.com` - the default for `betterspeedtest.sh` Note that the IPv4 address is shown first. But `ping 142.250.80.99` works fine, while neither `ping` nor `ping6` work for the IPv6 address (unsurprising, because I have no v6 connectivity).

```
root# nslookup gstatic.com
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:      gstatic.com
Address 1: 142.250.80.99
Address 2: 2607:f8b0:4006:80d::2003
```
